/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: notebook.proto */

#ifndef PROTOBUF_C_notebook_2eproto__INCLUDED
#define PROTOBUF_C_notebook_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Notebook__Cell Notebook__Cell;
typedef struct Notebook__Page Notebook__Page;
typedef struct Notebook__StatusResponse Notebook__StatusResponse;
typedef struct Notebook__ListPagesResponse Notebook__ListPagesResponse;
typedef struct Notebook__GetPageResponse Notebook__GetPageResponse;
typedef struct Notebook__CreatePageRequest Notebook__CreatePageRequest;
typedef struct Notebook__CreatePageResponse Notebook__CreatePageResponse;
typedef struct Notebook__UpdatePageRequest Notebook__UpdatePageRequest;
typedef struct Notebook__DeletePageRequest Notebook__DeletePageRequest;
typedef struct Notebook__AddCellRequest Notebook__AddCellRequest;
typedef struct Notebook__AddCellResponse Notebook__AddCellResponse;
typedef struct Notebook__UpdateCellRequest Notebook__UpdateCellRequest;
typedef struct Notebook__DeleteCellRequest Notebook__DeleteCellRequest;
typedef struct Notebook__GetCellOutputRequest Notebook__GetCellOutputRequest;
typedef struct Notebook__GetCellOutputResponse Notebook__GetCellOutputResponse;
typedef struct Notebook__ExecCommandRequest Notebook__ExecCommandRequest;
typedef struct Notebook__ExecCommandResponse Notebook__ExecCommandResponse;
typedef struct Notebook__ExecScriptRequest Notebook__ExecScriptRequest;
typedef struct Notebook__ExecScriptResponse Notebook__ExecScriptResponse;
typedef struct Notebook__PipeRequest Notebook__PipeRequest;
typedef struct Notebook__PipeResponse Notebook__PipeResponse;
typedef struct Notebook__SettingsResponse Notebook__SettingsResponse;
typedef struct Notebook__SettingsResponse__EnvironmentEntry Notebook__SettingsResponse__EnvironmentEntry;
typedef struct Notebook__SetSettingRequest Notebook__SetSettingRequest;
typedef struct Notebook__DeleteSettingRequest Notebook__DeleteSettingRequest;
typedef struct Notebook__ErrorResponse Notebook__ErrorResponse;
typedef struct Notebook__SuccessResponse Notebook__SuccessResponse;


/* --- enums --- */

/*
 * CellType enumerates the kinds of notebook cells.
 */
typedef enum _Notebook__CellType {
  NOTEBOOK__CELL_TYPE__CELL_TYPE_UNSPECIFIED = 0,
  NOTEBOOK__CELL_TYPE__CELL_TYPE_COMMAND = 1,
  NOTEBOOK__CELL_TYPE__CELL_TYPE_SCRIPT = 2,
  NOTEBOOK__CELL_TYPE__CELL_TYPE_MARKDOWN = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NOTEBOOK__CELL_TYPE)
} Notebook__CellType;

/* --- messages --- */

/*
 * Cell represents a single notebook cell (command, script, or markdown).
 */
struct  Notebook__Cell
{
  ProtobufCMessage base;
  /*
   * Unique cell identifier (8-char nonce).
   */
  char *id;
  /*
   * Cell type.
   */
  Notebook__CellType type;
  /*
   * Command string, script source, or markdown text.
   */
  char *content;
  /*
   * Raw execution output (ANSI bytes for cmd/script, rendered HTML for markdown).
   */
  ProtobufCBinaryData output;
  /*
   * Unix timestamp of creation.
   */
  int64_t created;
  /*
   * Unix timestamp of last execution (0 if never).
   */
  int64_t executed;
};
#define NOTEBOOK__CELL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__cell__descriptor) \
, (char *)protobuf_c_empty_string, NOTEBOOK__CELL_TYPE__CELL_TYPE_UNSPECIFIED, (char *)protobuf_c_empty_string, {0,NULL}, 0, 0 }


/*
 * Page represents a notebook page containing cells and associated binary.
 */
struct  Notebook__Page
{
  ProtobufCMessage base;
  /*
   * Unique page identifier (32-char nonce).
   */
  char *id;
  /*
   * Human-readable page title.
   */
  char *title;
  /*
   * Original filename of the uploaded binary.
   */
  char *filename;
  /*
   * Storage key for the binary file.
   */
  char *binary;
  /*
   * Whether a Rizin pipe is currently open.
   */
  protobuf_c_boolean pipe;
  /*
   * Unix timestamp of creation.
   */
  int64_t created;
  /*
   * Unix timestamp of last modification.
   */
  int64_t modified;
  /*
   * Ordered list of cells.
   */
  size_t n_cells;
  Notebook__Cell **cells;
};
#define NOTEBOOK__PAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__page__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, 0,NULL }


/*
 * StatusResponse is returned by the health/status endpoint.
 */
struct  Notebook__StatusResponse
{
  ProtobufCMessage base;
  /*
   * Notebook server version string.
   */
  char *version;
  /*
   * Rizin version string.
   */
  char *rizin_version;
  /*
   * Resolved path to rizin binary.
   */
  char *rizin_path;
  /*
   * Notebook data directory path.
   */
  char *storage;
  /*
   * Total number of pages.
   */
  int32_t pages;
  /*
   * Number of currently open Rizin pipes.
   */
  int32_t open_pipes;
};
#define NOTEBOOK__STATUS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__status_response__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0 }


/*
 * ListPagesResponse contains a summary of all pages.
 */
struct  Notebook__ListPagesResponse
{
  ProtobufCMessage base;
  size_t n_pages;
  Notebook__Page **pages;
};
#define NOTEBOOK__LIST_PAGES_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__list_pages_response__descriptor) \
, 0,NULL }


/*
 * GetPageResponse returns a single page with all cells.
 */
struct  Notebook__GetPageResponse
{
  ProtobufCMessage base;
  Notebook__Page *page;
};
#define NOTEBOOK__GET_PAGE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__get_page_response__descriptor) \
, NULL }


/*
 * CreatePageRequest creates a new notebook page.
 */
struct  Notebook__CreatePageRequest
{
  ProtobufCMessage base;
  /*
   * Required: page title.
   */
  char *title;
  /*
   * Required: original binary filename.
   */
  char *filename;
  /*
   * Required: binary file content.
   */
  ProtobufCBinaryData binary;
};
#define NOTEBOOK__CREATE_PAGE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__create_page_request__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL} }


/*
 * CreatePageResponse returns the created page.
 */
struct  Notebook__CreatePageResponse
{
  ProtobufCMessage base;
  Notebook__Page *page;
};
#define NOTEBOOK__CREATE_PAGE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__create_page_response__descriptor) \
, NULL }


/*
 * UpdatePageRequest modifies page metadata.
 */
struct  Notebook__UpdatePageRequest
{
  ProtobufCMessage base;
  /*
   * Required: page ID.
   */
  char *id;
  /*
   * New title (if non-empty).
   */
  char *title;
};
#define NOTEBOOK__UPDATE_PAGE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__update_page_request__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * DeletePageRequest removes a page and all its cells.
 */
struct  Notebook__DeletePageRequest
{
  ProtobufCMessage base;
  /*
   * Required: page ID.
   */
  char *id;
};
#define NOTEBOOK__DELETE_PAGE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__delete_page_request__descriptor) \
, (char *)protobuf_c_empty_string }


/*
 * AddCellRequest adds a new cell to a page.
 */
struct  Notebook__AddCellRequest
{
  ProtobufCMessage base;
  /*
   * Required: parent page ID.
   */
  char *page_id;
  /*
   * Required: cell type.
   */
  Notebook__CellType type;
  /*
   * Command, script source, or initial markdown.
   */
  char *content;
};
#define NOTEBOOK__ADD_CELL_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__add_cell_request__descriptor) \
, (char *)protobuf_c_empty_string, NOTEBOOK__CELL_TYPE__CELL_TYPE_UNSPECIFIED, (char *)protobuf_c_empty_string }


/*
 * AddCellResponse returns the created cell.
 */
struct  Notebook__AddCellResponse
{
  ProtobufCMessage base;
  Notebook__Cell *cell;
};
#define NOTEBOOK__ADD_CELL_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__add_cell_response__descriptor) \
, NULL }


/*
 * UpdateCellRequest modifies a cell's content.
 */
struct  Notebook__UpdateCellRequest
{
  ProtobufCMessage base;
  /*
   * Required: parent page ID.
   */
  char *page_id;
  /*
   * Required: cell ID.
   */
  char *cell_id;
  /*
   * New content (command, script, or markdown).
   */
  char *content;
};
#define NOTEBOOK__UPDATE_CELL_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__update_cell_request__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * DeleteCellRequest removes a cell from a page.
 */
struct  Notebook__DeleteCellRequest
{
  ProtobufCMessage base;
  /*
   * Required: parent page ID.
   */
  char *page_id;
  /*
   * Required: cell ID.
   */
  char *cell_id;
};
#define NOTEBOOK__DELETE_CELL_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__delete_cell_request__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * GetCellOutputRequest retrieves the output of a cell.
 */
struct  Notebook__GetCellOutputRequest
{
  ProtobufCMessage base;
  char *page_id;
  char *cell_id;
};
#define NOTEBOOK__GET_CELL_OUTPUT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__get_cell_output_request__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * GetCellOutputResponse returns raw output bytes.
 */
struct  Notebook__GetCellOutputResponse
{
  ProtobufCMessage base;
  /*
   * Raw ANSI output bytes.
   */
  ProtobufCBinaryData output;
  /*
   * Pre-rendered HTML (ANSI-to-HTML converted).
   */
  char *html;
  /*
   * Unix timestamp of execution.
   */
  int64_t executed_at;
};
#define NOTEBOOK__GET_CELL_OUTPUT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__get_cell_output_response__descriptor) \
, {0,NULL}, (char *)protobuf_c_empty_string, 0 }


/*
 * ExecCommandRequest executes a rizin command and stores result as a cell.
 */
struct  Notebook__ExecCommandRequest
{
  ProtobufCMessage base;
  /*
   * Required: page ID (must have open pipe).
   */
  char *page_id;
  /*
   * Required: rizin command string.
   */
  char *command;
};
#define NOTEBOOK__EXEC_COMMAND_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__exec_command_request__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * ExecCommandResponse returns execution result.
 */
struct  Notebook__ExecCommandResponse
{
  ProtobufCMessage base;
  /*
   * The created command cell with output.
   */
  Notebook__Cell *cell;
  /*
   * Whether execution succeeded.
   */
  protobuf_c_boolean success;
  /*
   * Error message if failed.
   */
  char *error;
};
#define NOTEBOOK__EXEC_COMMAND_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__exec_command_response__descriptor) \
, NULL, 0, (char *)protobuf_c_empty_string }


/*
 * ExecScriptRequest executes a JavaScript script.
 */
struct  Notebook__ExecScriptRequest
{
  ProtobufCMessage base;
  /*
   * Required: page ID.
   */
  char *page_id;
  /*
   * Required: JavaScript source code.
   */
  char *script;
};
#define NOTEBOOK__EXEC_SCRIPT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__exec_script_request__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * ExecScriptResponse returns script execution result.
 */
struct  Notebook__ExecScriptResponse
{
  ProtobufCMessage base;
  /*
   * The created script cell with output.
   */
  Notebook__Cell *cell;
  protobuf_c_boolean success;
  char *error;
};
#define NOTEBOOK__EXEC_SCRIPT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__exec_script_response__descriptor) \
, NULL, 0, (char *)protobuf_c_empty_string }


/*
 * PipeRequest opens or closes a Rizin pipe for a page.
 */
struct  Notebook__PipeRequest
{
  ProtobufCMessage base;
  /*
   * Required: page ID.
   */
  char *page_id;
};
#define NOTEBOOK__PIPE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__pipe_request__descriptor) \
, (char *)protobuf_c_empty_string }


/*
 * PipeResponse reports pipe status.
 */
struct  Notebook__PipeResponse
{
  ProtobufCMessage base;
  /*
   * Whether the pipe is now open.
   */
  protobuf_c_boolean open;
  /*
   * Error message if operation failed.
   */
  char *error;
};
#define NOTEBOOK__PIPE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__pipe_response__descriptor) \
, 0, (char *)protobuf_c_empty_string }


struct  Notebook__SettingsResponse__EnvironmentEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define NOTEBOOK__SETTINGS_RESPONSE__ENVIRONMENT_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__settings_response__environment_entry__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * SettingsResponse returns all environment variable settings.
 */
struct  Notebook__SettingsResponse
{
  ProtobufCMessage base;
  size_t n_environment;
  Notebook__SettingsResponse__EnvironmentEntry **environment;
};
#define NOTEBOOK__SETTINGS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__settings_response__descriptor) \
, 0,NULL }


/*
 * SetSettingRequest sets an environment variable.
 */
struct  Notebook__SetSettingRequest
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define NOTEBOOK__SET_SETTING_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__set_setting_request__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * DeleteSettingRequest removes an environment variable.
 */
struct  Notebook__DeleteSettingRequest
{
  ProtobufCMessage base;
  char *key;
};
#define NOTEBOOK__DELETE_SETTING_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__delete_setting_request__descriptor) \
, (char *)protobuf_c_empty_string }


/*
 * ErrorResponse is returned on any API error.
 */
struct  Notebook__ErrorResponse
{
  ProtobufCMessage base;
  /*
   * HTTP status code.
   */
  int32_t code;
  /*
   * Human-readable error description.
   */
  char *message;
};
#define NOTEBOOK__ERROR_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__error_response__descriptor) \
, 0, (char *)protobuf_c_empty_string }


/*
 * SuccessResponse is a generic acknowledgement.
 */
struct  Notebook__SuccessResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean ok;
  char *message;
};
#define NOTEBOOK__SUCCESS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notebook__success_response__descriptor) \
, 0, (char *)protobuf_c_empty_string }


/* Notebook__Cell methods */
void   notebook__cell__init
                     (Notebook__Cell         *message);
size_t notebook__cell__get_packed_size
                     (const Notebook__Cell   *message);
size_t notebook__cell__pack
                     (const Notebook__Cell   *message,
                      uint8_t             *out);
size_t notebook__cell__pack_to_buffer
                     (const Notebook__Cell   *message,
                      ProtobufCBuffer     *buffer);
Notebook__Cell *
       notebook__cell__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__cell__free_unpacked
                     (Notebook__Cell *message,
                      ProtobufCAllocator *allocator);
/* Notebook__Page methods */
void   notebook__page__init
                     (Notebook__Page         *message);
size_t notebook__page__get_packed_size
                     (const Notebook__Page   *message);
size_t notebook__page__pack
                     (const Notebook__Page   *message,
                      uint8_t             *out);
size_t notebook__page__pack_to_buffer
                     (const Notebook__Page   *message,
                      ProtobufCBuffer     *buffer);
Notebook__Page *
       notebook__page__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__page__free_unpacked
                     (Notebook__Page *message,
                      ProtobufCAllocator *allocator);
/* Notebook__StatusResponse methods */
void   notebook__status_response__init
                     (Notebook__StatusResponse         *message);
size_t notebook__status_response__get_packed_size
                     (const Notebook__StatusResponse   *message);
size_t notebook__status_response__pack
                     (const Notebook__StatusResponse   *message,
                      uint8_t             *out);
size_t notebook__status_response__pack_to_buffer
                     (const Notebook__StatusResponse   *message,
                      ProtobufCBuffer     *buffer);
Notebook__StatusResponse *
       notebook__status_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__status_response__free_unpacked
                     (Notebook__StatusResponse *message,
                      ProtobufCAllocator *allocator);
/* Notebook__ListPagesResponse methods */
void   notebook__list_pages_response__init
                     (Notebook__ListPagesResponse         *message);
size_t notebook__list_pages_response__get_packed_size
                     (const Notebook__ListPagesResponse   *message);
size_t notebook__list_pages_response__pack
                     (const Notebook__ListPagesResponse   *message,
                      uint8_t             *out);
size_t notebook__list_pages_response__pack_to_buffer
                     (const Notebook__ListPagesResponse   *message,
                      ProtobufCBuffer     *buffer);
Notebook__ListPagesResponse *
       notebook__list_pages_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__list_pages_response__free_unpacked
                     (Notebook__ListPagesResponse *message,
                      ProtobufCAllocator *allocator);
/* Notebook__GetPageResponse methods */
void   notebook__get_page_response__init
                     (Notebook__GetPageResponse         *message);
size_t notebook__get_page_response__get_packed_size
                     (const Notebook__GetPageResponse   *message);
size_t notebook__get_page_response__pack
                     (const Notebook__GetPageResponse   *message,
                      uint8_t             *out);
size_t notebook__get_page_response__pack_to_buffer
                     (const Notebook__GetPageResponse   *message,
                      ProtobufCBuffer     *buffer);
Notebook__GetPageResponse *
       notebook__get_page_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__get_page_response__free_unpacked
                     (Notebook__GetPageResponse *message,
                      ProtobufCAllocator *allocator);
/* Notebook__CreatePageRequest methods */
void   notebook__create_page_request__init
                     (Notebook__CreatePageRequest         *message);
size_t notebook__create_page_request__get_packed_size
                     (const Notebook__CreatePageRequest   *message);
size_t notebook__create_page_request__pack
                     (const Notebook__CreatePageRequest   *message,
                      uint8_t             *out);
size_t notebook__create_page_request__pack_to_buffer
                     (const Notebook__CreatePageRequest   *message,
                      ProtobufCBuffer     *buffer);
Notebook__CreatePageRequest *
       notebook__create_page_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__create_page_request__free_unpacked
                     (Notebook__CreatePageRequest *message,
                      ProtobufCAllocator *allocator);
/* Notebook__CreatePageResponse methods */
void   notebook__create_page_response__init
                     (Notebook__CreatePageResponse         *message);
size_t notebook__create_page_response__get_packed_size
                     (const Notebook__CreatePageResponse   *message);
size_t notebook__create_page_response__pack
                     (const Notebook__CreatePageResponse   *message,
                      uint8_t             *out);
size_t notebook__create_page_response__pack_to_buffer
                     (const Notebook__CreatePageResponse   *message,
                      ProtobufCBuffer     *buffer);
Notebook__CreatePageResponse *
       notebook__create_page_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__create_page_response__free_unpacked
                     (Notebook__CreatePageResponse *message,
                      ProtobufCAllocator *allocator);
/* Notebook__UpdatePageRequest methods */
void   notebook__update_page_request__init
                     (Notebook__UpdatePageRequest         *message);
size_t notebook__update_page_request__get_packed_size
                     (const Notebook__UpdatePageRequest   *message);
size_t notebook__update_page_request__pack
                     (const Notebook__UpdatePageRequest   *message,
                      uint8_t             *out);
size_t notebook__update_page_request__pack_to_buffer
                     (const Notebook__UpdatePageRequest   *message,
                      ProtobufCBuffer     *buffer);
Notebook__UpdatePageRequest *
       notebook__update_page_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__update_page_request__free_unpacked
                     (Notebook__UpdatePageRequest *message,
                      ProtobufCAllocator *allocator);
/* Notebook__DeletePageRequest methods */
void   notebook__delete_page_request__init
                     (Notebook__DeletePageRequest         *message);
size_t notebook__delete_page_request__get_packed_size
                     (const Notebook__DeletePageRequest   *message);
size_t notebook__delete_page_request__pack
                     (const Notebook__DeletePageRequest   *message,
                      uint8_t             *out);
size_t notebook__delete_page_request__pack_to_buffer
                     (const Notebook__DeletePageRequest   *message,
                      ProtobufCBuffer     *buffer);
Notebook__DeletePageRequest *
       notebook__delete_page_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__delete_page_request__free_unpacked
                     (Notebook__DeletePageRequest *message,
                      ProtobufCAllocator *allocator);
/* Notebook__AddCellRequest methods */
void   notebook__add_cell_request__init
                     (Notebook__AddCellRequest         *message);
size_t notebook__add_cell_request__get_packed_size
                     (const Notebook__AddCellRequest   *message);
size_t notebook__add_cell_request__pack
                     (const Notebook__AddCellRequest   *message,
                      uint8_t             *out);
size_t notebook__add_cell_request__pack_to_buffer
                     (const Notebook__AddCellRequest   *message,
                      ProtobufCBuffer     *buffer);
Notebook__AddCellRequest *
       notebook__add_cell_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__add_cell_request__free_unpacked
                     (Notebook__AddCellRequest *message,
                      ProtobufCAllocator *allocator);
/* Notebook__AddCellResponse methods */
void   notebook__add_cell_response__init
                     (Notebook__AddCellResponse         *message);
size_t notebook__add_cell_response__get_packed_size
                     (const Notebook__AddCellResponse   *message);
size_t notebook__add_cell_response__pack
                     (const Notebook__AddCellResponse   *message,
                      uint8_t             *out);
size_t notebook__add_cell_response__pack_to_buffer
                     (const Notebook__AddCellResponse   *message,
                      ProtobufCBuffer     *buffer);
Notebook__AddCellResponse *
       notebook__add_cell_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__add_cell_response__free_unpacked
                     (Notebook__AddCellResponse *message,
                      ProtobufCAllocator *allocator);
/* Notebook__UpdateCellRequest methods */
void   notebook__update_cell_request__init
                     (Notebook__UpdateCellRequest         *message);
size_t notebook__update_cell_request__get_packed_size
                     (const Notebook__UpdateCellRequest   *message);
size_t notebook__update_cell_request__pack
                     (const Notebook__UpdateCellRequest   *message,
                      uint8_t             *out);
size_t notebook__update_cell_request__pack_to_buffer
                     (const Notebook__UpdateCellRequest   *message,
                      ProtobufCBuffer     *buffer);
Notebook__UpdateCellRequest *
       notebook__update_cell_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__update_cell_request__free_unpacked
                     (Notebook__UpdateCellRequest *message,
                      ProtobufCAllocator *allocator);
/* Notebook__DeleteCellRequest methods */
void   notebook__delete_cell_request__init
                     (Notebook__DeleteCellRequest         *message);
size_t notebook__delete_cell_request__get_packed_size
                     (const Notebook__DeleteCellRequest   *message);
size_t notebook__delete_cell_request__pack
                     (const Notebook__DeleteCellRequest   *message,
                      uint8_t             *out);
size_t notebook__delete_cell_request__pack_to_buffer
                     (const Notebook__DeleteCellRequest   *message,
                      ProtobufCBuffer     *buffer);
Notebook__DeleteCellRequest *
       notebook__delete_cell_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__delete_cell_request__free_unpacked
                     (Notebook__DeleteCellRequest *message,
                      ProtobufCAllocator *allocator);
/* Notebook__GetCellOutputRequest methods */
void   notebook__get_cell_output_request__init
                     (Notebook__GetCellOutputRequest         *message);
size_t notebook__get_cell_output_request__get_packed_size
                     (const Notebook__GetCellOutputRequest   *message);
size_t notebook__get_cell_output_request__pack
                     (const Notebook__GetCellOutputRequest   *message,
                      uint8_t             *out);
size_t notebook__get_cell_output_request__pack_to_buffer
                     (const Notebook__GetCellOutputRequest   *message,
                      ProtobufCBuffer     *buffer);
Notebook__GetCellOutputRequest *
       notebook__get_cell_output_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__get_cell_output_request__free_unpacked
                     (Notebook__GetCellOutputRequest *message,
                      ProtobufCAllocator *allocator);
/* Notebook__GetCellOutputResponse methods */
void   notebook__get_cell_output_response__init
                     (Notebook__GetCellOutputResponse         *message);
size_t notebook__get_cell_output_response__get_packed_size
                     (const Notebook__GetCellOutputResponse   *message);
size_t notebook__get_cell_output_response__pack
                     (const Notebook__GetCellOutputResponse   *message,
                      uint8_t             *out);
size_t notebook__get_cell_output_response__pack_to_buffer
                     (const Notebook__GetCellOutputResponse   *message,
                      ProtobufCBuffer     *buffer);
Notebook__GetCellOutputResponse *
       notebook__get_cell_output_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__get_cell_output_response__free_unpacked
                     (Notebook__GetCellOutputResponse *message,
                      ProtobufCAllocator *allocator);
/* Notebook__ExecCommandRequest methods */
void   notebook__exec_command_request__init
                     (Notebook__ExecCommandRequest         *message);
size_t notebook__exec_command_request__get_packed_size
                     (const Notebook__ExecCommandRequest   *message);
size_t notebook__exec_command_request__pack
                     (const Notebook__ExecCommandRequest   *message,
                      uint8_t             *out);
size_t notebook__exec_command_request__pack_to_buffer
                     (const Notebook__ExecCommandRequest   *message,
                      ProtobufCBuffer     *buffer);
Notebook__ExecCommandRequest *
       notebook__exec_command_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__exec_command_request__free_unpacked
                     (Notebook__ExecCommandRequest *message,
                      ProtobufCAllocator *allocator);
/* Notebook__ExecCommandResponse methods */
void   notebook__exec_command_response__init
                     (Notebook__ExecCommandResponse         *message);
size_t notebook__exec_command_response__get_packed_size
                     (const Notebook__ExecCommandResponse   *message);
size_t notebook__exec_command_response__pack
                     (const Notebook__ExecCommandResponse   *message,
                      uint8_t             *out);
size_t notebook__exec_command_response__pack_to_buffer
                     (const Notebook__ExecCommandResponse   *message,
                      ProtobufCBuffer     *buffer);
Notebook__ExecCommandResponse *
       notebook__exec_command_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__exec_command_response__free_unpacked
                     (Notebook__ExecCommandResponse *message,
                      ProtobufCAllocator *allocator);
/* Notebook__ExecScriptRequest methods */
void   notebook__exec_script_request__init
                     (Notebook__ExecScriptRequest         *message);
size_t notebook__exec_script_request__get_packed_size
                     (const Notebook__ExecScriptRequest   *message);
size_t notebook__exec_script_request__pack
                     (const Notebook__ExecScriptRequest   *message,
                      uint8_t             *out);
size_t notebook__exec_script_request__pack_to_buffer
                     (const Notebook__ExecScriptRequest   *message,
                      ProtobufCBuffer     *buffer);
Notebook__ExecScriptRequest *
       notebook__exec_script_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__exec_script_request__free_unpacked
                     (Notebook__ExecScriptRequest *message,
                      ProtobufCAllocator *allocator);
/* Notebook__ExecScriptResponse methods */
void   notebook__exec_script_response__init
                     (Notebook__ExecScriptResponse         *message);
size_t notebook__exec_script_response__get_packed_size
                     (const Notebook__ExecScriptResponse   *message);
size_t notebook__exec_script_response__pack
                     (const Notebook__ExecScriptResponse   *message,
                      uint8_t             *out);
size_t notebook__exec_script_response__pack_to_buffer
                     (const Notebook__ExecScriptResponse   *message,
                      ProtobufCBuffer     *buffer);
Notebook__ExecScriptResponse *
       notebook__exec_script_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__exec_script_response__free_unpacked
                     (Notebook__ExecScriptResponse *message,
                      ProtobufCAllocator *allocator);
/* Notebook__PipeRequest methods */
void   notebook__pipe_request__init
                     (Notebook__PipeRequest         *message);
size_t notebook__pipe_request__get_packed_size
                     (const Notebook__PipeRequest   *message);
size_t notebook__pipe_request__pack
                     (const Notebook__PipeRequest   *message,
                      uint8_t             *out);
size_t notebook__pipe_request__pack_to_buffer
                     (const Notebook__PipeRequest   *message,
                      ProtobufCBuffer     *buffer);
Notebook__PipeRequest *
       notebook__pipe_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__pipe_request__free_unpacked
                     (Notebook__PipeRequest *message,
                      ProtobufCAllocator *allocator);
/* Notebook__PipeResponse methods */
void   notebook__pipe_response__init
                     (Notebook__PipeResponse         *message);
size_t notebook__pipe_response__get_packed_size
                     (const Notebook__PipeResponse   *message);
size_t notebook__pipe_response__pack
                     (const Notebook__PipeResponse   *message,
                      uint8_t             *out);
size_t notebook__pipe_response__pack_to_buffer
                     (const Notebook__PipeResponse   *message,
                      ProtobufCBuffer     *buffer);
Notebook__PipeResponse *
       notebook__pipe_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__pipe_response__free_unpacked
                     (Notebook__PipeResponse *message,
                      ProtobufCAllocator *allocator);
/* Notebook__SettingsResponse__EnvironmentEntry methods */
void   notebook__settings_response__environment_entry__init
                     (Notebook__SettingsResponse__EnvironmentEntry         *message);
/* Notebook__SettingsResponse methods */
void   notebook__settings_response__init
                     (Notebook__SettingsResponse         *message);
size_t notebook__settings_response__get_packed_size
                     (const Notebook__SettingsResponse   *message);
size_t notebook__settings_response__pack
                     (const Notebook__SettingsResponse   *message,
                      uint8_t             *out);
size_t notebook__settings_response__pack_to_buffer
                     (const Notebook__SettingsResponse   *message,
                      ProtobufCBuffer     *buffer);
Notebook__SettingsResponse *
       notebook__settings_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__settings_response__free_unpacked
                     (Notebook__SettingsResponse *message,
                      ProtobufCAllocator *allocator);
/* Notebook__SetSettingRequest methods */
void   notebook__set_setting_request__init
                     (Notebook__SetSettingRequest         *message);
size_t notebook__set_setting_request__get_packed_size
                     (const Notebook__SetSettingRequest   *message);
size_t notebook__set_setting_request__pack
                     (const Notebook__SetSettingRequest   *message,
                      uint8_t             *out);
size_t notebook__set_setting_request__pack_to_buffer
                     (const Notebook__SetSettingRequest   *message,
                      ProtobufCBuffer     *buffer);
Notebook__SetSettingRequest *
       notebook__set_setting_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__set_setting_request__free_unpacked
                     (Notebook__SetSettingRequest *message,
                      ProtobufCAllocator *allocator);
/* Notebook__DeleteSettingRequest methods */
void   notebook__delete_setting_request__init
                     (Notebook__DeleteSettingRequest         *message);
size_t notebook__delete_setting_request__get_packed_size
                     (const Notebook__DeleteSettingRequest   *message);
size_t notebook__delete_setting_request__pack
                     (const Notebook__DeleteSettingRequest   *message,
                      uint8_t             *out);
size_t notebook__delete_setting_request__pack_to_buffer
                     (const Notebook__DeleteSettingRequest   *message,
                      ProtobufCBuffer     *buffer);
Notebook__DeleteSettingRequest *
       notebook__delete_setting_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__delete_setting_request__free_unpacked
                     (Notebook__DeleteSettingRequest *message,
                      ProtobufCAllocator *allocator);
/* Notebook__ErrorResponse methods */
void   notebook__error_response__init
                     (Notebook__ErrorResponse         *message);
size_t notebook__error_response__get_packed_size
                     (const Notebook__ErrorResponse   *message);
size_t notebook__error_response__pack
                     (const Notebook__ErrorResponse   *message,
                      uint8_t             *out);
size_t notebook__error_response__pack_to_buffer
                     (const Notebook__ErrorResponse   *message,
                      ProtobufCBuffer     *buffer);
Notebook__ErrorResponse *
       notebook__error_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__error_response__free_unpacked
                     (Notebook__ErrorResponse *message,
                      ProtobufCAllocator *allocator);
/* Notebook__SuccessResponse methods */
void   notebook__success_response__init
                     (Notebook__SuccessResponse         *message);
size_t notebook__success_response__get_packed_size
                     (const Notebook__SuccessResponse   *message);
size_t notebook__success_response__pack
                     (const Notebook__SuccessResponse   *message,
                      uint8_t             *out);
size_t notebook__success_response__pack_to_buffer
                     (const Notebook__SuccessResponse   *message,
                      ProtobufCBuffer     *buffer);
Notebook__SuccessResponse *
       notebook__success_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notebook__success_response__free_unpacked
                     (Notebook__SuccessResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Notebook__Cell_Closure)
                 (const Notebook__Cell *message,
                  void *closure_data);
typedef void (*Notebook__Page_Closure)
                 (const Notebook__Page *message,
                  void *closure_data);
typedef void (*Notebook__StatusResponse_Closure)
                 (const Notebook__StatusResponse *message,
                  void *closure_data);
typedef void (*Notebook__ListPagesResponse_Closure)
                 (const Notebook__ListPagesResponse *message,
                  void *closure_data);
typedef void (*Notebook__GetPageResponse_Closure)
                 (const Notebook__GetPageResponse *message,
                  void *closure_data);
typedef void (*Notebook__CreatePageRequest_Closure)
                 (const Notebook__CreatePageRequest *message,
                  void *closure_data);
typedef void (*Notebook__CreatePageResponse_Closure)
                 (const Notebook__CreatePageResponse *message,
                  void *closure_data);
typedef void (*Notebook__UpdatePageRequest_Closure)
                 (const Notebook__UpdatePageRequest *message,
                  void *closure_data);
typedef void (*Notebook__DeletePageRequest_Closure)
                 (const Notebook__DeletePageRequest *message,
                  void *closure_data);
typedef void (*Notebook__AddCellRequest_Closure)
                 (const Notebook__AddCellRequest *message,
                  void *closure_data);
typedef void (*Notebook__AddCellResponse_Closure)
                 (const Notebook__AddCellResponse *message,
                  void *closure_data);
typedef void (*Notebook__UpdateCellRequest_Closure)
                 (const Notebook__UpdateCellRequest *message,
                  void *closure_data);
typedef void (*Notebook__DeleteCellRequest_Closure)
                 (const Notebook__DeleteCellRequest *message,
                  void *closure_data);
typedef void (*Notebook__GetCellOutputRequest_Closure)
                 (const Notebook__GetCellOutputRequest *message,
                  void *closure_data);
typedef void (*Notebook__GetCellOutputResponse_Closure)
                 (const Notebook__GetCellOutputResponse *message,
                  void *closure_data);
typedef void (*Notebook__ExecCommandRequest_Closure)
                 (const Notebook__ExecCommandRequest *message,
                  void *closure_data);
typedef void (*Notebook__ExecCommandResponse_Closure)
                 (const Notebook__ExecCommandResponse *message,
                  void *closure_data);
typedef void (*Notebook__ExecScriptRequest_Closure)
                 (const Notebook__ExecScriptRequest *message,
                  void *closure_data);
typedef void (*Notebook__ExecScriptResponse_Closure)
                 (const Notebook__ExecScriptResponse *message,
                  void *closure_data);
typedef void (*Notebook__PipeRequest_Closure)
                 (const Notebook__PipeRequest *message,
                  void *closure_data);
typedef void (*Notebook__PipeResponse_Closure)
                 (const Notebook__PipeResponse *message,
                  void *closure_data);
typedef void (*Notebook__SettingsResponse__EnvironmentEntry_Closure)
                 (const Notebook__SettingsResponse__EnvironmentEntry *message,
                  void *closure_data);
typedef void (*Notebook__SettingsResponse_Closure)
                 (const Notebook__SettingsResponse *message,
                  void *closure_data);
typedef void (*Notebook__SetSettingRequest_Closure)
                 (const Notebook__SetSettingRequest *message,
                  void *closure_data);
typedef void (*Notebook__DeleteSettingRequest_Closure)
                 (const Notebook__DeleteSettingRequest *message,
                  void *closure_data);
typedef void (*Notebook__ErrorResponse_Closure)
                 (const Notebook__ErrorResponse *message,
                  void *closure_data);
typedef void (*Notebook__SuccessResponse_Closure)
                 (const Notebook__SuccessResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    notebook__cell_type__descriptor;
extern const ProtobufCMessageDescriptor notebook__cell__descriptor;
extern const ProtobufCMessageDescriptor notebook__page__descriptor;
extern const ProtobufCMessageDescriptor notebook__status_response__descriptor;
extern const ProtobufCMessageDescriptor notebook__list_pages_response__descriptor;
extern const ProtobufCMessageDescriptor notebook__get_page_response__descriptor;
extern const ProtobufCMessageDescriptor notebook__create_page_request__descriptor;
extern const ProtobufCMessageDescriptor notebook__create_page_response__descriptor;
extern const ProtobufCMessageDescriptor notebook__update_page_request__descriptor;
extern const ProtobufCMessageDescriptor notebook__delete_page_request__descriptor;
extern const ProtobufCMessageDescriptor notebook__add_cell_request__descriptor;
extern const ProtobufCMessageDescriptor notebook__add_cell_response__descriptor;
extern const ProtobufCMessageDescriptor notebook__update_cell_request__descriptor;
extern const ProtobufCMessageDescriptor notebook__delete_cell_request__descriptor;
extern const ProtobufCMessageDescriptor notebook__get_cell_output_request__descriptor;
extern const ProtobufCMessageDescriptor notebook__get_cell_output_response__descriptor;
extern const ProtobufCMessageDescriptor notebook__exec_command_request__descriptor;
extern const ProtobufCMessageDescriptor notebook__exec_command_response__descriptor;
extern const ProtobufCMessageDescriptor notebook__exec_script_request__descriptor;
extern const ProtobufCMessageDescriptor notebook__exec_script_response__descriptor;
extern const ProtobufCMessageDescriptor notebook__pipe_request__descriptor;
extern const ProtobufCMessageDescriptor notebook__pipe_response__descriptor;
extern const ProtobufCMessageDescriptor notebook__settings_response__descriptor;
extern const ProtobufCMessageDescriptor notebook__settings_response__environment_entry__descriptor;
extern const ProtobufCMessageDescriptor notebook__set_setting_request__descriptor;
extern const ProtobufCMessageDescriptor notebook__delete_setting_request__descriptor;
extern const ProtobufCMessageDescriptor notebook__error_response__descriptor;
extern const ProtobufCMessageDescriptor notebook__success_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_notebook_2eproto__INCLUDED */
