// Protocol Buffers schema for rizin-notebook API.
// All API endpoints accept and return protobuf-encoded messages.
// Content-Type: application/x-protobuf

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/notebook.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CellType enumerates the kinds of notebook cells.
type CellType int32

const (
	CellType_CELL_TYPE_UNSPECIFIED CellType = 0
	CellType_CELL_TYPE_COMMAND     CellType = 1
	CellType_CELL_TYPE_SCRIPT      CellType = 2
	CellType_CELL_TYPE_MARKDOWN    CellType = 3
)

// Enum value maps for CellType.
var (
	CellType_name = map[int32]string{
		0: "CELL_TYPE_UNSPECIFIED",
		1: "CELL_TYPE_COMMAND",
		2: "CELL_TYPE_SCRIPT",
		3: "CELL_TYPE_MARKDOWN",
	}
	CellType_value = map[string]int32{
		"CELL_TYPE_UNSPECIFIED": 0,
		"CELL_TYPE_COMMAND":     1,
		"CELL_TYPE_SCRIPT":      2,
		"CELL_TYPE_MARKDOWN":    3,
	}
)

func (x CellType) Enum() *CellType {
	p := new(CellType)
	*p = x
	return p
}

func (x CellType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CellType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notebook_proto_enumTypes[0].Descriptor()
}

func (CellType) Type() protoreflect.EnumType {
	return &file_proto_notebook_proto_enumTypes[0]
}

func (x CellType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CellType.Descriptor instead.
func (CellType) EnumDescriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{0}
}

// Cell represents a single notebook cell (command, script, or markdown).
type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                             // Unique cell identifier (8-char nonce).
	Type          CellType               `protobuf:"varint,2,opt,name=type,proto3,enum=notebook.CellType" json:"type,omitempty"` // Cell type.
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                   // Command string, script source, or markdown text.
	Output        []byte                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`                     // Raw execution output (ANSI bytes for cmd/script, rendered HTML for markdown).
	Created       int64                  `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`                  // Unix timestamp of creation.
	Executed      int64                  `protobuf:"varint,6,opt,name=executed,proto3" json:"executed,omitempty"`                // Unix timestamp of last execution (0 if never).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_proto_notebook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{0}
}

func (x *Cell) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cell) GetType() CellType {
	if x != nil {
		return x.Type
	}
	return CellType_CELL_TYPE_UNSPECIFIED
}

func (x *Cell) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Cell) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Cell) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *Cell) GetExecuted() int64 {
	if x != nil {
		return x.Executed
	}
	return 0
}

// Page represents a notebook page containing cells and associated binary.
type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`              // Unique page identifier (32-char nonce).
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`        // Human-readable page title.
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`  // Original filename of the uploaded binary.
	Binary        string                 `protobuf:"bytes,4,opt,name=binary,proto3" json:"binary,omitempty"`      // Storage key for the binary file.
	Pipe          bool                   `protobuf:"varint,5,opt,name=pipe,proto3" json:"pipe,omitempty"`         // Whether a Rizin pipe is currently open.
	Created       int64                  `protobuf:"varint,6,opt,name=created,proto3" json:"created,omitempty"`   // Unix timestamp of creation.
	Modified      int64                  `protobuf:"varint,7,opt,name=modified,proto3" json:"modified,omitempty"` // Unix timestamp of last modification.
	Cells         []*Cell                `protobuf:"bytes,8,rep,name=cells,proto3" json:"cells,omitempty"`        // Ordered list of cells.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_proto_notebook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{1}
}

func (x *Page) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Page) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Page) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Page) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *Page) GetPipe() bool {
	if x != nil {
		return x.Pipe
	}
	return false
}

func (x *Page) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *Page) GetModified() int64 {
	if x != nil {
		return x.Modified
	}
	return 0
}

func (x *Page) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

// StatusResponse is returned by the health/status endpoint.
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                               // Notebook server version string.
	RizinVersion  string                 `protobuf:"bytes,2,opt,name=rizin_version,json=rizinVersion,proto3" json:"rizin_version,omitempty"` // Rizin version string.
	RizinPath     string                 `protobuf:"bytes,3,opt,name=rizin_path,json=rizinPath,proto3" json:"rizin_path,omitempty"`          // Resolved path to rizin binary.
	Storage       string                 `protobuf:"bytes,4,opt,name=storage,proto3" json:"storage,omitempty"`                               // Notebook data directory path.
	Pages         int32                  `protobuf:"varint,5,opt,name=pages,proto3" json:"pages,omitempty"`                                  // Total number of pages.
	OpenPipes     int32                  `protobuf:"varint,6,opt,name=open_pipes,json=openPipes,proto3" json:"open_pipes,omitempty"`         // Number of currently open Rizin pipes.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_notebook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetRizinVersion() string {
	if x != nil {
		return x.RizinVersion
	}
	return ""
}

func (x *StatusResponse) GetRizinPath() string {
	if x != nil {
		return x.RizinPath
	}
	return ""
}

func (x *StatusResponse) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *StatusResponse) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *StatusResponse) GetOpenPipes() int32 {
	if x != nil {
		return x.OpenPipes
	}
	return 0
}

// ListPagesResponse contains a summary of all pages.
type ListPagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         []*Page                `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPagesResponse) Reset() {
	*x = ListPagesResponse{}
	mi := &file_proto_notebook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagesResponse) ProtoMessage() {}

func (x *ListPagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagesResponse.ProtoReflect.Descriptor instead.
func (*ListPagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{3}
}

func (x *ListPagesResponse) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

// GetPageResponse returns a single page with all cells.
type GetPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageResponse) Reset() {
	*x = GetPageResponse{}
	mi := &file_proto_notebook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageResponse) ProtoMessage() {}

func (x *GetPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageResponse.ProtoReflect.Descriptor instead.
func (*GetPageResponse) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{4}
}

func (x *GetPageResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

// CreatePageRequest creates a new notebook page.
type CreatePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`       // Required: page title.
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"` // Required: original binary filename.
	Binary        []byte                 `protobuf:"bytes,3,opt,name=binary,proto3" json:"binary,omitempty"`     // Required: binary file content.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePageRequest) Reset() {
	*x = CreatePageRequest{}
	mi := &file_proto_notebook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePageRequest) ProtoMessage() {}

func (x *CreatePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePageRequest.ProtoReflect.Descriptor instead.
func (*CreatePageRequest) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CreatePageRequest) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

// CreatePageResponse returns the created page.
type CreatePageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePageResponse) Reset() {
	*x = CreatePageResponse{}
	mi := &file_proto_notebook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePageResponse) ProtoMessage() {}

func (x *CreatePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePageResponse.ProtoReflect.Descriptor instead.
func (*CreatePageResponse) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePageResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

// UpdatePageRequest modifies page metadata.
type UpdatePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`       // Required: page ID.
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"` // New title (if non-empty).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePageRequest) Reset() {
	*x = UpdatePageRequest{}
	mi := &file_proto_notebook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePageRequest) ProtoMessage() {}

func (x *UpdatePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePageRequest.ProtoReflect.Descriptor instead.
func (*UpdatePageRequest) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// DeletePageRequest removes a page and all its cells.
type DeletePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Required: page ID.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePageRequest) Reset() {
	*x = DeletePageRequest{}
	mi := &file_proto_notebook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePageRequest) ProtoMessage() {}

func (x *DeletePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePageRequest.ProtoReflect.Descriptor instead.
func (*DeletePageRequest) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// AddCellRequest adds a new cell to a page.
type AddCellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`       // Required: parent page ID.
	Type          CellType               `protobuf:"varint,2,opt,name=type,proto3,enum=notebook.CellType" json:"type,omitempty"` // Required: cell type.
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                   // Command, script source, or initial markdown.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCellRequest) Reset() {
	*x = AddCellRequest{}
	mi := &file_proto_notebook_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCellRequest) ProtoMessage() {}

func (x *AddCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCellRequest.ProtoReflect.Descriptor instead.
func (*AddCellRequest) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{9}
}

func (x *AddCellRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *AddCellRequest) GetType() CellType {
	if x != nil {
		return x.Type
	}
	return CellType_CELL_TYPE_UNSPECIFIED
}

func (x *AddCellRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// AddCellResponse returns the created cell.
type AddCellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cell          *Cell                  `protobuf:"bytes,1,opt,name=cell,proto3" json:"cell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCellResponse) Reset() {
	*x = AddCellResponse{}
	mi := &file_proto_notebook_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCellResponse) ProtoMessage() {}

func (x *AddCellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCellResponse.ProtoReflect.Descriptor instead.
func (*AddCellResponse) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{10}
}

func (x *AddCellResponse) GetCell() *Cell {
	if x != nil {
		return x.Cell
	}
	return nil
}

// UpdateCellRequest modifies a cell's content.
type UpdateCellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"` // Required: parent page ID.
	CellId        string                 `protobuf:"bytes,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"` // Required: cell ID.
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`             // New content (command, script, or markdown).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCellRequest) Reset() {
	*x = UpdateCellRequest{}
	mi := &file_proto_notebook_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCellRequest) ProtoMessage() {}

func (x *UpdateCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCellRequest.ProtoReflect.Descriptor instead.
func (*UpdateCellRequest) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateCellRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *UpdateCellRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *UpdateCellRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// DeleteCellRequest removes a cell from a page.
type DeleteCellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"` // Required: parent page ID.
	CellId        string                 `protobuf:"bytes,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"` // Required: cell ID.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCellRequest) Reset() {
	*x = DeleteCellRequest{}
	mi := &file_proto_notebook_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCellRequest) ProtoMessage() {}

func (x *DeleteCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCellRequest.ProtoReflect.Descriptor instead.
func (*DeleteCellRequest) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCellRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *DeleteCellRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

// GetCellOutputRequest retrieves the output of a cell.
type GetCellOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	CellId        string                 `protobuf:"bytes,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellOutputRequest) Reset() {
	*x = GetCellOutputRequest{}
	mi := &file_proto_notebook_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellOutputRequest) ProtoMessage() {}

func (x *GetCellOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellOutputRequest.ProtoReflect.Descriptor instead.
func (*GetCellOutputRequest) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{13}
}

func (x *GetCellOutputRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *GetCellOutputRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

// GetCellOutputResponse returns raw output bytes.
type GetCellOutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`                            // Raw ANSI output bytes.
	Html          string                 `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty"`                                // Pre-rendered HTML (ANSI-to-HTML converted).
	ExecutedAt    int64                  `protobuf:"varint,3,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"` // Unix timestamp of execution.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellOutputResponse) Reset() {
	*x = GetCellOutputResponse{}
	mi := &file_proto_notebook_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellOutputResponse) ProtoMessage() {}

func (x *GetCellOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellOutputResponse.ProtoReflect.Descriptor instead.
func (*GetCellOutputResponse) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{14}
}

func (x *GetCellOutputResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *GetCellOutputResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *GetCellOutputResponse) GetExecutedAt() int64 {
	if x != nil {
		return x.ExecutedAt
	}
	return 0
}

// ExecCommandRequest executes a rizin command and stores result as a cell.
type ExecCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"` // Required: page ID (must have open pipe).
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`             // Required: rizin command string.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommandRequest) Reset() {
	*x = ExecCommandRequest{}
	mi := &file_proto_notebook_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommandRequest) ProtoMessage() {}

func (x *ExecCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{15}
}

func (x *ExecCommandRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *ExecCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// ExecCommandResponse returns execution result.
type ExecCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cell          *Cell                  `protobuf:"bytes,1,opt,name=cell,proto3" json:"cell,omitempty"`        // The created command cell with output.
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // Whether execution succeeded.
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`      // Error message if failed.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommandResponse) Reset() {
	*x = ExecCommandResponse{}
	mi := &file_proto_notebook_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommandResponse) ProtoMessage() {}

func (x *ExecCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecCommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{16}
}

func (x *ExecCommandResponse) GetCell() *Cell {
	if x != nil {
		return x.Cell
	}
	return nil
}

func (x *ExecCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecCommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ExecScriptRequest executes a JavaScript script.
type ExecScriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"` // Required: page ID.
	Script        string                 `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`               // Required: JavaScript source code.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecScriptRequest) Reset() {
	*x = ExecScriptRequest{}
	mi := &file_proto_notebook_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecScriptRequest) ProtoMessage() {}

func (x *ExecScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecScriptRequest.ProtoReflect.Descriptor instead.
func (*ExecScriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{17}
}

func (x *ExecScriptRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *ExecScriptRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

// ExecScriptResponse returns script execution result.
type ExecScriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cell          *Cell                  `protobuf:"bytes,1,opt,name=cell,proto3" json:"cell,omitempty"` // The created script cell with output.
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecScriptResponse) Reset() {
	*x = ExecScriptResponse{}
	mi := &file_proto_notebook_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecScriptResponse) ProtoMessage() {}

func (x *ExecScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecScriptResponse.ProtoReflect.Descriptor instead.
func (*ExecScriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{18}
}

func (x *ExecScriptResponse) GetCell() *Cell {
	if x != nil {
		return x.Cell
	}
	return nil
}

func (x *ExecScriptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecScriptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// PipeRequest opens or closes a Rizin pipe for a page.
type PipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"` // Required: page ID.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeRequest) Reset() {
	*x = PipeRequest{}
	mi := &file_proto_notebook_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeRequest) ProtoMessage() {}

func (x *PipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeRequest.ProtoReflect.Descriptor instead.
func (*PipeRequest) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{19}
}

func (x *PipeRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

// PipeResponse reports pipe status.
type PipeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          bool                   `protobuf:"varint,1,opt,name=open,proto3" json:"open,omitempty"`  // Whether the pipe is now open.
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Error message if operation failed.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeResponse) Reset() {
	*x = PipeResponse{}
	mi := &file_proto_notebook_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeResponse) ProtoMessage() {}

func (x *PipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeResponse.ProtoReflect.Descriptor instead.
func (*PipeResponse) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{20}
}

func (x *PipeResponse) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *PipeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SettingsResponse returns all environment variable settings.
type SettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   map[string]string      `protobuf:"bytes,1,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsResponse) Reset() {
	*x = SettingsResponse{}
	mi := &file_proto_notebook_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsResponse) ProtoMessage() {}

func (x *SettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsResponse.ProtoReflect.Descriptor instead.
func (*SettingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{21}
}

func (x *SettingsResponse) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

// SetSettingRequest sets an environment variable.
type SetSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSettingRequest) Reset() {
	*x = SetSettingRequest{}
	mi := &file_proto_notebook_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSettingRequest) ProtoMessage() {}

func (x *SetSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSettingRequest.ProtoReflect.Descriptor instead.
func (*SetSettingRequest) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{22}
}

func (x *SetSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetSettingRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// DeleteSettingRequest removes an environment variable.
type DeleteSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSettingRequest) Reset() {
	*x = DeleteSettingRequest{}
	mi := &file_proto_notebook_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSettingRequest) ProtoMessage() {}

func (x *DeleteSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSettingRequest.ProtoReflect.Descriptor instead.
func (*DeleteSettingRequest) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// ErrorResponse is returned on any API error.
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // HTTP status code.
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Human-readable error description.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_notebook_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{24}
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SuccessResponse is a generic acknowledgement.
type SuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessResponse) Reset() {
	*x = SuccessResponse{}
	mi := &file_proto_notebook_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResponse) ProtoMessage() {}

func (x *SuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notebook_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResponse.ProtoReflect.Descriptor instead.
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_notebook_proto_rawDescGZIP(), []int{25}
}

func (x *SuccessResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SuccessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_notebook_proto protoreflect.FileDescriptor

const file_proto_notebook_proto_rawDesc = "" +
	"\n" +
	"\x14proto/notebook.proto\x12\bnotebook\"\xa6\x01\n" +
	"\x04Cell\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.notebook.CellTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06output\x18\x04 \x01(\fR\x06output\x12\x18\n" +
	"\acreated\x18\x05 \x01(\x03R\acreated\x12\x1a\n" +
	"\bexecuted\x18\x06 \x01(\x03R\bexecuted\"\xd0\x01\n" +
	"\x04Page\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x16\n" +
	"\x06binary\x18\x04 \x01(\tR\x06binary\x12\x12\n" +
	"\x04pipe\x18\x05 \x01(\bR\x04pipe\x12\x18\n" +
	"\acreated\x18\x06 \x01(\x03R\acreated\x12\x1a\n" +
	"\bmodified\x18\a \x01(\x03R\bmodified\x12$\n" +
	"\x05cells\x18\b \x03(\v2\x0e.notebook.CellR\x05cells\"\xbd\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12#\n" +
	"\rrizin_version\x18\x02 \x01(\tR\frizinVersion\x12\x1d\n" +
	"\n" +
	"rizin_path\x18\x03 \x01(\tR\trizinPath\x12\x18\n" +
	"\astorage\x18\x04 \x01(\tR\astorage\x12\x14\n" +
	"\x05pages\x18\x05 \x01(\x05R\x05pages\x12\x1d\n" +
	"\n" +
	"open_pipes\x18\x06 \x01(\x05R\topenPipes\"9\n" +
	"\x11ListPagesResponse\x12$\n" +
	"\x05pages\x18\x01 \x03(\v2\x0e.notebook.PageR\x05pages\"5\n" +
	"\x0fGetPageResponse\x12\"\n" +
	"\x04page\x18\x01 \x01(\v2\x0e.notebook.PageR\x04page\"]\n" +
	"\x11CreatePageRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x16\n" +
	"\x06binary\x18\x03 \x01(\fR\x06binary\"8\n" +
	"\x12CreatePageResponse\x12\"\n" +
	"\x04page\x18\x01 \x01(\v2\x0e.notebook.PageR\x04page\"9\n" +
	"\x11UpdatePageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"#\n" +
	"\x11DeletePageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"k\n" +
	"\x0eAddCellRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.notebook.CellTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"5\n" +
	"\x0fAddCellResponse\x12\"\n" +
	"\x04cell\x18\x01 \x01(\v2\x0e.notebook.CellR\x04cell\"_\n" +
	"\x11UpdateCellRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\tR\x06cellId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"E\n" +
	"\x11DeleteCellRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\tR\x06cellId\"H\n" +
	"\x14GetCellOutputRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\tR\x06cellId\"d\n" +
	"\x15GetCellOutputResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\x12\x12\n" +
	"\x04html\x18\x02 \x01(\tR\x04html\x12\x1f\n" +
	"\vexecuted_at\x18\x03 \x01(\x03R\n" +
	"executedAt\"G\n" +
	"\x12ExecCommandRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"i\n" +
	"\x13ExecCommandResponse\x12\"\n" +
	"\x04cell\x18\x01 \x01(\v2\x0e.notebook.CellR\x04cell\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"D\n" +
	"\x11ExecScriptRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x16\n" +
	"\x06script\x18\x02 \x01(\tR\x06script\"h\n" +
	"\x12ExecScriptResponse\x12\"\n" +
	"\x04cell\x18\x01 \x01(\v2\x0e.notebook.CellR\x04cell\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"&\n" +
	"\vPipeRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\"8\n" +
	"\fPipeResponse\x12\x12\n" +
	"\x04open\x18\x01 \x01(\bR\x04open\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa1\x01\n" +
	"\x10SettingsResponse\x12M\n" +
	"\venvironment\x18\x01 \x03(\v2+.notebook.SettingsResponse.EnvironmentEntryR\venvironment\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\x11SetSettingRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"(\n" +
	"\x14DeleteSettingRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\";\n" +
	"\x0fSuccessResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*j\n" +
	"\bCellType\x12\x19\n" +
	"\x15CELL_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CELL_TYPE_COMMAND\x10\x01\x12\x14\n" +
	"\x10CELL_TYPE_SCRIPT\x10\x02\x12\x16\n" +
	"\x12CELL_TYPE_MARKDOWN\x10\x03B'Z%github.com/rizinorg/rizin-notebook/pbb\x06proto3"

var (
	file_proto_notebook_proto_rawDescOnce sync.Once
	file_proto_notebook_proto_rawDescData []byte
)

func file_proto_notebook_proto_rawDescGZIP() []byte {
	file_proto_notebook_proto_rawDescOnce.Do(func() {
		file_proto_notebook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notebook_proto_rawDesc), len(file_proto_notebook_proto_rawDesc)))
	})
	return file_proto_notebook_proto_rawDescData
}

var file_proto_notebook_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_notebook_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_notebook_proto_goTypes = []any{
	(CellType)(0),                 // 0: notebook.CellType
	(*Cell)(nil),                  // 1: notebook.Cell
	(*Page)(nil),                  // 2: notebook.Page
	(*StatusResponse)(nil),        // 3: notebook.StatusResponse
	(*ListPagesResponse)(nil),     // 4: notebook.ListPagesResponse
	(*GetPageResponse)(nil),       // 5: notebook.GetPageResponse
	(*CreatePageRequest)(nil),     // 6: notebook.CreatePageRequest
	(*CreatePageResponse)(nil),    // 7: notebook.CreatePageResponse
	(*UpdatePageRequest)(nil),     // 8: notebook.UpdatePageRequest
	(*DeletePageRequest)(nil),     // 9: notebook.DeletePageRequest
	(*AddCellRequest)(nil),        // 10: notebook.AddCellRequest
	(*AddCellResponse)(nil),       // 11: notebook.AddCellResponse
	(*UpdateCellRequest)(nil),     // 12: notebook.UpdateCellRequest
	(*DeleteCellRequest)(nil),     // 13: notebook.DeleteCellRequest
	(*GetCellOutputRequest)(nil),  // 14: notebook.GetCellOutputRequest
	(*GetCellOutputResponse)(nil), // 15: notebook.GetCellOutputResponse
	(*ExecCommandRequest)(nil),    // 16: notebook.ExecCommandRequest
	(*ExecCommandResponse)(nil),   // 17: notebook.ExecCommandResponse
	(*ExecScriptRequest)(nil),     // 18: notebook.ExecScriptRequest
	(*ExecScriptResponse)(nil),    // 19: notebook.ExecScriptResponse
	(*PipeRequest)(nil),           // 20: notebook.PipeRequest
	(*PipeResponse)(nil),          // 21: notebook.PipeResponse
	(*SettingsResponse)(nil),      // 22: notebook.SettingsResponse
	(*SetSettingRequest)(nil),     // 23: notebook.SetSettingRequest
	(*DeleteSettingRequest)(nil),  // 24: notebook.DeleteSettingRequest
	(*ErrorResponse)(nil),         // 25: notebook.ErrorResponse
	(*SuccessResponse)(nil),       // 26: notebook.SuccessResponse
	nil,                           // 27: notebook.SettingsResponse.EnvironmentEntry
}
var file_proto_notebook_proto_depIdxs = []int32{
	0,  // 0: notebook.Cell.type:type_name -> notebook.CellType
	1,  // 1: notebook.Page.cells:type_name -> notebook.Cell
	2,  // 2: notebook.ListPagesResponse.pages:type_name -> notebook.Page
	2,  // 3: notebook.GetPageResponse.page:type_name -> notebook.Page
	2,  // 4: notebook.CreatePageResponse.page:type_name -> notebook.Page
	0,  // 5: notebook.AddCellRequest.type:type_name -> notebook.CellType
	1,  // 6: notebook.AddCellResponse.cell:type_name -> notebook.Cell
	1,  // 7: notebook.ExecCommandResponse.cell:type_name -> notebook.Cell
	1,  // 8: notebook.ExecScriptResponse.cell:type_name -> notebook.Cell
	27, // 9: notebook.SettingsResponse.environment:type_name -> notebook.SettingsResponse.EnvironmentEntry
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_notebook_proto_init() }
func file_proto_notebook_proto_init() {
	if File_proto_notebook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notebook_proto_rawDesc), len(file_proto_notebook_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_notebook_proto_goTypes,
		DependencyIndexes: file_proto_notebook_proto_depIdxs,
		EnumInfos:         file_proto_notebook_proto_enumTypes,
		MessageInfos:      file_proto_notebook_proto_msgTypes,
	}.Build()
	File_proto_notebook_proto = out.File
	file_proto_notebook_proto_goTypes = nil
	file_proto_notebook_proto_depIdxs = nil
}
